services:
  mongo:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  user-student-service:
    build: ./user-student-service
    ports:
      - "3001:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/students_db
      - TOKEN_SECRET=KinalMedicSuperSecretaParaJWT2024!!Segura
    depends_on:
      - mongo

  medical-records-service:
    build: ./medical-records-service
    ports:
      - "3002:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/medical_db
      - TOKEN_SECRET=KinalMedicSuperSecretaParaJWT2024!!Segura
    depends_on:
      - mongo

  inventory-service:
    build: ./inventory-service
    ports:
      - "3003:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/inventory_db
      - JWT_SECRET=KinalMedicSuperSecretaParaJWT2024!!Segura
      - JWT_ISSUER=KinalMedic
      - JWT_AUDIENCE=KinalMedic
    depends_on:
      - mongo

  availability-service:
    build: 
      context: ./availability-service
      dockerfile: Dockerfile
    ports:
      - "3004:8080"
    environment:
      - JWT_SECRET=KinalMedicSuperSecretaParaJWT2024!!Segura
      - ConnectionStrings__MongoDb=mongodb://mongo:27017
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - mongo

  notification-service:
    build: ./notification-service
    container_name: kinalmedic-notification-service
    ports:
      - "3005:3000"
    environment:
      - PORT=3000
      - EMAIL_USER=programingteam70@gmail.com
      - EMAIL_PASS=fstc wpzh frpp fooi
    depends_on:
      - mongo

  medic-admin:
    build:
      context: ./medic-admin
      dockerfile: Dockerfile
    container_name: kinalmedic_frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_AUTH_URL=http://localhost:3001/api/students
      - VITE_ADMIN_URL=http://localhost:3001/api/students
      - VITE_MEDICAL_RECORDS_URL=http://localhost:3002/api/records
      - VITE_INVENTORY_API_URL=http://localhost:3003/inv/medicine
      - VITE_AVAILABILITY_URL=http://localhost:3004/api/availability
      - VITE_NOTIFICATION_URL=http://localhost:3005/api/notifications
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./medic-admin:/app
      - /app/node_modules
    depends_on:
      - user-student-service
      - availability-service
volumes:
  mongo_data: